---
abstract: 'a server-side solution for the jQuery DataTables plugin'
author:
  - 'Adam Hopkins <srchulo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl_5
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DataTables
no_index:
  directory:
    - t
    - inc
requires:
  CGI: 3.6
  Carp: 0
  DBI: 1.611
  JSON::XS: 2.32
version: 0.02
